"""empty message

Revision ID: 456a37c92cf1
Revises: 513fbc28ef38
Create Date: 2023-08-15 20:45:51.105720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456a37c92cf1'
down_revision = '513fbc28ef38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=False))
        batch_op.drop_constraint('blog_post_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('blog_post_category_id_fkey', 'work_type', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###
