"""Initial migration.

Revision ID: 513fbc28ef38
Revises: 67cf935dfefd
Create Date: 2023-03-14 16:22:36.496999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513fbc28ef38'
down_revision = '67cf935dfefd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id_rating', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('apply_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['apply_id'], ['blog_apply.id_apply'], ),
    sa.PrimaryKeyConstraint('id_rating')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
